services:

  redis:
    image: redis:7.2.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - cobe-network
    restart: always

  db:
    image: postgres:15-alpine
    container_name: postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cobe-network
    restart: always

  api:
    image: cobe-api
    container_name: spring
    build:
      context: ./api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      LOGGING_DIR_PATH: ${LOGGING_DIR_PATH}
    ports:
      - "9000:8080"
    volumes:
      - ./api/logs:/logs
      - uploaded_files:/app/uploads
    depends_on:
      - db
    networks:
      - cobe-network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - cobe-network
    restart: always

  # Nouveau service NGINX pour l'application Angular
  spa:
    build:
      context: ./spa
      dockerfile: Dockerfile
    container_name: angular
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - cobe-network
    restart: always

networks:
  cobe-network:
    driver: bridge

volumes:
  pg_data:
  uploaded_files: